version: "1.0"

services:
  webmeteo_simulation:
    image: selenium-python
    container_name: webmeteo_simulation
    #restart: always
    volumes:
      - ./bin:/usr/src/app/
    command: >
        bash -c "set -v
                cd /usr/src/app/
                python3 WebMeteo_simulation.py"
    networks:
        tap:

networks:
    tap:
        external: true