version: "1.0"

services:
  webmeteo_simulation:
    build:
      context: ./selenium-python
      dockerfile: Dockerfile
    container_name: webmeteo_simulation
    #restart: always
    volumes:
      - ./webmeteo_simulation/bin:/usr/src/app/
    command: >
        bash -c "set -v
                cd /usr/src/app/
                python3 WebMeteo_simulation.py"
    networks:
        tap:

networks:
    tap:
        external: true