version: "1.0"

services:
  kafka_zookeeper:
    container_name: kafka_zookeeper
    build:
      context: ./kakfa/kafka_image
      dockerfile: Dockerfile
    ports:
      - 2181:2181
    command: > 
      bash -c "set -v
               mkdir -p /tmp/zookeeper
               cd /opt/kafka
               zookeeper-server-start.sh config/zookeeper.properties"
    networks:
      tap:
        ipv4_address: 10.0.100.22

  kafka_ui:
    build:
      context: kafka_ui
      dockerfile: Dockerfile.UI
    depends_on:
      - kafka_zookeeper
    container_name: kafka_ui
    ports:
      - 8080:8080
    networks:
      tap:
        ipv4_address: 10.0.100.20
  

  kafka_broker:
    build:
      context: ./kakfa/kafka_image
      dockerfile: Dockerfile
    container_name: kafka_broker
    depends_on:
      - kafka_zookeeper
      - kafka_ui
    ports:
      - 9092:9092
    command: > 
      bash -c "set -v
               cd /opt/kafka
               kafka-server-start.sh config/server.properties"
    networks:
      tap:
        ipv4_address: 10.0.100.23

  web_meteo_topics:
    build:
      context: ./kakfa/kafka_image
      dockerfile: Dockerfile
    container_name: web_meteo_topics
    command: > 
      bash -c "set -v
               cd /opt/kafka
               kafka-topics.sh --bootstrap-server 10.0.100.23:9092 --list
               kafka-topics.sh --create --bootstrap-server 10.0.100.23:9092 --replication-factor 1 --partitions 1 --topic web_image
               kafka-topics.sh --create --bootstrap-server 10.0.100.23:9092 --replication-factor 1 --partitions 1 --topic web_data
               kafka-topics.sh --create --bootstrap-server 10.0.100.23:9092 --replication-factor 1 --partitions 2 --topic restart_request
               kafka-topics.sh --bootstrap-server 10.0.100.23:9092 --list"
    depends_on: 
        - kafka_zookeeper
        - kafka_ui
        - kafka_broker
    networks:
      tap:

networks:
    tap:
        external: true